MUSARK-925 Use MuseumId in dao
MUSIT-Norway/musit pull request #263
Opened 2017-03-09 15:06 UTC by jarlah

2017-03-09 15:09 UTC, jarlah commented
Kommentar på  denne saken av line: 
NB må tenke på om det har noe å si at flere actors har samme UUID

er dette noe vi skal tenke på? hvordan kan det være et problem? og har det noe med å skille på museumId?

2017-03-09 15:31 UTC, ingarabr commented on service_actor/app/repositories/dao/ActorDao.scala
> +      (a.fn.toLowerCase like s"%$likeArg%") && a.museumId === mid.underlying
You can remove the `underlying` call by changing the setup of the table to read the Int to a `MuseumId` (line 82 in this file). You also need to add a Column type for `MuseumId` in `ColumnTypeMappers`

2017-03-09 18:34 UTC, kpmeen requested changes

2017-03-09 18:34 UTC, kpmeen commented on service_actor/app/repositories/dao/ActorDao.scala
> +      (a.fn.toLowerCase like s"%$likeArg%") && a.museumId === mid.underlying
Mmm...I also see we have a job to do to update the return types of the public methods here. But that's an issue in itself, really.

2017-03-09 18:34 UTC, kpmeen commented on service_actor/app/repositories/dao/UserInfoDao.scala
> +import no.uio.musit.models.{ActorId, MuseumId}
Unused import?

2017-03-09 18:34 UTC, kpmeen commented on service_actor/test/resources/evolutions/test/1.sql
> +INSERT INTO MUSIT_MAPPING.ACTOR (ACTORNAME, DATAPORTEN_UUID, DATAPORTEN_USERNAME, APPLICATION_UUID, MUSEUM_ID)
Have you double checked with @ellenjo that the `MUSEUM_ID` column is available in `MUSIT_MAPPING.ACTOR` table?

2017-03-09 19:05 UTC, jarlah commented on service_actor/test/resources/evolutions/test/1.sql
> +INSERT INTO MUSIT_MAPPING.ACTOR (ACTORNAME, DATAPORTEN_UUID, DATAPORTEN_USERNAME, APPLICATION_UUID, MUSEUM_ID)
ill check this tomorrow. If not then this is pretty useless work :)

2017-03-10 07:49 UTC, kpmeen commented on service_actor/test/resources/evolutions/test/1.sql
> +INSERT INTO MUSIT_MAPPING.ACTOR (ACTORNAME, DATAPORTEN_UUID, DATAPORTEN_USERNAME, APPLICATION_UUID, MUSEUM_ID)
Checked the `MUSIT_MAPPING.ACTOR` table just now, and there is indeed a column for museumId there. However, you'll need to change it's spelling.
But apparently it's not called `MUSEUM_ID` in that particular table, but `MUSEUMID`.

2017-03-10 07:51 UTC, kpmeen commented on service_actor/test/resources/evolutions/test/1.sql
> +INSERT INTO MUSIT_MAPPING.ACTOR (ACTORNAME, DATAPORTEN_UUID, DATAPORTEN_USERNAME, APPLICATION_UUID, MUSEUM_ID)
Checked the `MUSIT_MAPPING.ACTOR` table on UTV now, and the column is indeed there.

2017-03-10 07:52 UTC, kpmeen approved these changes

2017-03-10 07:52 UTC, merged