MUSARK-959 - feature/uniform urls
MUSIT-Norway/musit pull request #280
Opened 2017-03-24 11:05 UTC by ingarabr

2017-03-24 12:44 UTC, jarlah reviewed
Not really convinced that its the right solution to continue support v1 urls. The best is to demand changes in the client

2017-03-24 17:15 UTC, kpmeen commented
@jarlah we can't do that due to the Delphi client depending on the moveObject service. So until we know all installations of the KHM app has been updated with new URL, we have to have the v1 path in the config. The web client should not be allowed to use the v1 uri's though.

2017-03-24 17:20 UTC, kpmeen requested changes

2017-03-24 17:20 UTC, kpmeen commented on docker/dev/nginx/nginx.conf
> +      proxy_pass http://actor:7070/service_actor/;
Only the storagefacility service should have a v1 mapping enabled. The only reason is for the Delphi client not to break.

2017-03-24 17:20 UTC, kpmeen commented on docker/dev/nginx/nginx.conf
> +      proxy_pass http://geolocation:7070/service_geo_location/;
See below comment

2017-03-24 17:20 UTC, kpmeen commented on docker/utv/nginx/nginx.conf
> +      proxy_pass http://geolocation:7070/service_geo_location/;
See comment in dev nginx above

2017-03-27 12:15 UTC, kpmeen commented
@ingarabr please rebase and update the PR

2017-03-27 13:34 UTC, steinaol approved these changes
LGTM

2017-03-27 13:37 UTC, kpmeen approved these changes

2017-03-27 13:37 UTC, merged