MUSARK-998 - feature/analysis missing fields
MUSIT-Norway/musit pull request #305
Opened 2017-04-26 12:08 UTC by ingarabr

Related to MUSARK-998

Analysis collection:
- case number
- reason
- status

Sample created:
- external links

2017-04-26 18:56 UTC, kpmeen requested changes

2017-04-26 18:56 UTC, kpmeen commented on service_management/app/models/analysis/SampleStatuses.scala
> +        case Dehigdrated.key  => Some(Dehigdrated)
I think you mean `Dehydrated`, or?

2017-04-26 18:56 UTC, kpmeen commented on service_management/app/models/analysis/SampleStatuses.scala
> +: Ok, Oppbrukt, Kontaminert, Preparert, Kassert og Uttørket
I would add this as part of the comment for the `SampleStatuses` object, I think.

2017-04-26 18:56 UTC, kpmeen commented on service_management/conf/evolutions/default/1.sql
> +  status          NUMBER,
This should be `INTEGER` to ensure we're only adding integer numbers.

2017-04-26 18:56 UTC, kpmeen commented on docker/dev/oracle-init.sql
> +  status          NUMBER,
This should be `INTEGER`.

2017-04-26 18:56 UTC, kpmeen commented on service_management/test/resources/evolutions/test/1.sql
> +  status          NUMBER,
This should be `INTEGER`.

2017-04-26 19:17 UTC, ingarabr commented on service_management/app/models/analysis/SampleStatuses.scala
> +: Ok, Oppbrukt, Kontaminert, Preparert, Kassert og Uttørket
Note to self, remove temp comments before committing!

2017-04-27 09:12 UTC, kpmeen approved these changes

2017-04-27 09:12 UTC, merged